
- name: Validate kubeconfig file for local machine
  delegate_to: localhost
  block:
    - name: Check if file already exists
      ansible.builtin.stat:
        path: '{{ K8S_CONFIG }}'
      register: config_check

    - name: Fail if file already exists
      ansible.builtin.fail:
        msg: Kubeconfig file {{ K8S_CONFIG }} already exists
      when: config_check.stat.isreg is defined and config_check.stat.isreg

- name: Prepare K3S installation variables
  block:
    - name: Create K3S installation variables dictionary
      ansible.builtin.set_fact:
        K3S_INSTALLATION_VARS: {}

    - name: Add all user-defined variables to dictionary
      ansible.builtin.set_fact:
        K3S_INSTALLATION_VARS: '{{ K3S_INSTALLATION_VARS | combine({ "INSTALL_K3S_" + k3s_var.key: k3s_var.value  }) }}'
      loop: '{{ K3S.INSTALL | dict2items }}'
      loop_control:
        loop_var: k3s_var

## Deactivated due to EventRateLimit problems
# - name: Load configuration file on server
#   block:
#     - name: Create path to K3S configuration file
#       ansible.builtin.shell: mkdir -p '{{ k3s_dir_path }}'
#       loop:
#         - '/etc/rancher/k3s/'
#         - '/var/lib/rancher/k3s/server/'
#       loop_control:
#         loop_var: k3s_dir_path

#     - name: Copy configuration file to server
#       ansible.builtin.copy:
#         src: '{{ k3s_config_file.src }}'
#         dest: '{{ k3s_config_file.dest }}'
#         remote_src: false
#       loop:
#         - { src: files/00_config.yml, dest: /etc/rancher/k3s/config.yaml }
#         - { src: files/01_psa.yml,    dest: /var/lib/rancher/k3s/server/psa.yaml }
#         - { src: files/02_audit.yml,  dest: /var/lib/rancher/k3s/server/audit.yaml }
#       loop_control:
#         loop_var: k3s_config_file

- name: Install K3S
  ansible.builtin.shell: >-
    curl -sfL https://get.k3s.io | sh -s - --flannel-backend {{ K3S.FLANNEL_BACKEND }}
  register: debug_msg
  environment: '{{ K3S_INSTALLATION_VARS }}'

- name: Copy kubeconfig file from remote host to localhost
  no_log: '{{ ANSIBLE_NO_LOG }}'
  block:
    - name: Create directory ~/.kube if it doesn't exists
      delegate_to: localhost
      ansible.builtin.shell: mkdir -p ~/.kube
    
    - name: Copy kubeconfig to '{{ K8S_CONFIG }}'
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: '{{ K8S_CONFIG }}'
        flat: true
