- name: Fail if kubecontext is incorretly formatted
  ansible.builtin.fail:
    msg: Variable inv_k8s.context is incorrectly formatted, it should be in the form 'cluster-user'@'cluster-name'
  when: >-
    K8S_CONTEXT is not defined
    or
    K8S_CONTEXT == ""
    or 
    '@' not in K8S_CONTEXT

- name: Check if kubeconfig already exists
  block:
    - name: Check if kubeconfig already exists
      delegate_to: localhost
      ansible.builtin.stat:
        path: '{{ K8S_CONFIG }}'
      register: config_check

    - name: Fail if kubeconfig already exists
      delegate_to: localhost
      ansible.builtin.fail:
        msg: Kubeconfig file {{ K8S_CONFIG }} already exists, delete or rename it to proceed
      when: config_check.stat.isreg is defined and config_check.stat.isreg

- name: Process user data for user and cluster name
  block:
    - name: Split context into user and cluster name
      ansible.builtin.set_fact:
        K8S_USER_DATA: "{{ inv_k8s.context | split('@') }}"
    - name: Set kubeconfig user and cluster as vars
      ansible.builtin.set_fact:
        K8S_CLUSTER: "{{ inv_setup.kubeconfig.cluster | default('default')  }}"
        K8S_USER: "{{ inv_setup.kubeconfig.user | default('default')  }}"

- name: Load raw kubeconfig file into a variable
  block:
    - name: Read raw kubeconfig file
      ansible.builtin.slurp:
        src: /etc/rancher/k3s/k3s.yaml
      register: raw_kubeconfig

    - name: Load file into a variable for processing
      ansible.builtin.set_fact:
        raw_kubeconfig: "{{ raw_kubeconfig.content | b64decode | from_yaml }}"

- name: Create kubeconfig file
  delegate_to: localhost
  block:
    - name: Create directory ~/.kube if it doesn't exists
      ansible.builtin.shell: mkdir -p ~/.kube

    - name: Create file {{ K8S_CONFIG }}
      ansible.builtin.file:
        path: "{{ K8S_CONFIG }}"
        state: touch
        mode: 0644

    - name: Write data to kubeconfig file
      ansible.builtin.copy:
        content: "{{ lookup('template', 'templates/02_create_kubeconfig/kubeconfig.yml') }}"
        dest: "{{ K8S_CONFIG }}"
