############ To call tasks, use following template ############
# - name: Install Helm chart
#   ansible.builtin.import_tasks: tasks/templates/helm.yml
#   vars:
#     helm_repo_name:
#     helm_repo_url:
#     helm_release_namespace:
#     helm_release_name:
#     helm_chart_ref:
#     helm_chart_version:
#     helm_create_namespace:
#     helm_values_file:
#     helm_wait:
################################################################

# Template to apply helm chart
- name: Add helm repository {{ helm_repo_name }}
  kubernetes.core.helm_repository:
    kubeconfig: '{{ K8S_CONFIG }}'
    context: '{{ K8S_CONTEXT }}'
    repo_name: "{{ helm_repo_name }}"
    repo_url: "{{ helm_repo_url }}"
  register: add_helm_repo
  failed_when:
    - add_helm_repo.msg is defined
    - add_helm_repo.msg != ""
    - "'Repository already have a repository' not in add_helm_repo.msg"
  when: helm_repo_name is defined and helm_repo_url is defined

- name: Create helm installation for {{ helm_release_name }}
  kubernetes.core.helm:
    kubeconfig: '{{ K8S_CONFIG }}'
    context: '{{ K8S_CONTEXT }}'
    release_namespace: "{{ helm_release_namespace }}"
    release_name: "{{ helm_release_name }}"
    chart_ref: "{{ helm_chart_ref }}"
    chart_version: "{{ helm_chart_version }}"
    update_repo_cache: true
    create_namespace: "{{ helm_create_namespace }}"
    release_values: "{{ lookup('ansible.builtin.template', helm_values_file) | from_yaml }}"
    wait: '{{ helm_wait }}'