---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${cm_cluster_issuer_prd}
spec:
  acme:
    email: ${cm_email}
    profile: tlsserver
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: production-issuer-account-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: ${tr_gateway}
                namespace: ${ns_traefik}
                kind: Gateway
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${cm_cluster_issuer_stg}
spec:
  acme:
    email: ${cm_email}
    profile: tlsserver
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: staging-issuer-account-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: ${tr_gateway}
                namespace: ${ns_traefik}
                kind: Gateway
---