---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${K8S_CLUSTER_ISSUER_STG}
spec:
  acme:
    email: niveshramlochun055@gmail.com
    profile: tlsserver
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: staging-issuer-account-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: ${tr_gateway}
                namespace: ${ns_traefik}
                kind: Gateway
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${K8S_CLUSTER_ISSUER_PROD}
spec:
  acme:
    email: niveshramlochun055@gmail.com
    profile: tlsserver
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: production-issuer-account-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: ${tr_gateway}
                namespace: ${ns_traefik}
                kind: Gateway
---