- name: Install K3S
  hosts: main_server
  gather_facts: no

  vars_files:
    - vars/00_default.yml

  tasks:
    - name: Prepare server for K3S installation
      ansible.builtin.import_tasks: tasks/00_prepare_server.yml
      tags: [pre_install]

    - name: Install K3S on server
      ansible.builtin.import_tasks: tasks/01_install_k3s.yml
      tags: [install]

    - name: Uninstall K3S
      ansible.builtin.shell: /usr/local/bin/k3s-uninstall.sh
      tags: [never, uninstall]