---
# Database for keycloak
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: keycloak-db
  namespace: ${ENVIRONMENT}-${ns_iam}
spec:
  teamId: keycloak
  volume:
    storageClass: ${k8s_storage_class}
    size: 1Gi
  numberOfInstances: 1
  users:
    postgres:
      - superuser
      - createdb
      - createrole
  preparedDatabases:
    keycloak:
      defaultUsers: true
      schemas:
        keycloak_data:
          defaultUsers: false
  postgresql:
    version: "15"
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 50Mi
---
