apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-helm-values
data:
  values.yml: |-
    crds:
      enabled: true
      keep: true

    image:
      name: cert-manager-controller
      repository: quay.io/jetstack/cert-manager-controller
      tag: v1.20.2
      pullPolicy: IfNotPresent

    enableCertificateOwnerRef: true

    resources:
      requests:
        cpu: 20m
        memory: 40Mi
      limits:
        cpu: 40m
        memory: 60Mi

    prometheus:
      enabled: false

    webhook:
      replicaCount: 1

      resources:
        requests:
          cpu: 10m
          memory: 30Mi
        limits:
          cpu: 30m
          memory: 50Mi

      image:
        name: cert-manager-webhook
        repository: quay.io/jetstack/cert-manager-webhook
        tag: v1.20.2
        pullPolicy: IfNotPresent

    cainjector:
      replicaCount: 1

      resources:
        requests:
          cpu: 10m
          memory: 50Mi
        limits:
          cpu: 30m
          memory: 100Mi

      image:
        name: cert-manager-cainjector
        repository: quay.io/jetstack/cert-manager-cainjector
        tag: v1.20.2
        pullPolicy: IfNotPresent

    acmesolver:
      image:
        name: cert-manager-acmesolver
        repository: quay.io/jetstack/cert-manager-acmesolver
        tag: v1.20.2
        pullPolicy: IfNotPresent

    startupapicheck:
      enabled: true

      resources:
        requests:
          cpu: 10m
          memory: 30Mi
        limits:
          cpu: 30m
          memory: 50Mi

      image:
        name: cert-manager-startupapicheck
        repository: quay.io/jetstack/cert-manager-startupapicheck
        tag: v1.20.2
        pullPolicy: IfNotPresent
