kind: Config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: "{{ raw_kubeconfig.clusters[0].cluster['certificate-authority-data'] }}"
    server: "{{ raw_kubeconfig.clusters[0].cluster.server | replace('127.0.0.1', hostvars.main_server.ansible_host) }}"
  name: "{{ K8S_CLUSTER }}"
contexts:
- context:
    cluster: "{{ K8S_CLUSTER }}"
    user: "{{ K8S_USER }}"
  name: "{{ K8S_CONTEXT }}"
current-context: "{{ K8S_CONTEXT }}"
users:
- name: "{{ K8S_USER }}"
  user:
    client-certificate-data: "{{ raw_kubeconfig.users[0].user['client-certificate-data'] }}"
    client-key-data: "{{ raw_kubeconfig.users[0].user['client-key-data'] }}"