- name: Prepare Traefik deployment
  ansible.builtin.import_tasks: tasks/templates/prepare_deployment.yml
  vars:
    k8s_namespace: '{{ inv_traefik.namespace }}'
    k8s_component: Traefik

- name: Install Gateway API CRDs
  kubernetes.core.k8s:
    kubeconfig: '{{ K8S_CONFIG }}'
    context: '{{ K8S_CONTEXT }}'
    state: present
    src: https://github.com/kubernetes-sigs/gateway-api/releases/download/{{ software_ref.gateway_api.version }}/{{ software_ref.gateway_api.channel }}-install.yaml
    apply: true
    server_side_apply:
      field_manager: ansible

- name: Install Traefik CRDs
  kubernetes.core.k8s:
    kubeconfig: '{{ K8S_CONFIG }}'
    context: '{{ K8S_CONTEXT }}'
    state: present
    src: https://raw.githubusercontent.com/traefik/traefik/{{ software_ref.traefik.crd_version }}/docs/content/reference/dynamic-configuration/kubernetes-gateway-rbac.yml
    apply: true
    server_side_apply:
      field_manager: ansible

- name: Install Traefik
  ansible.builtin.import_tasks: tasks/templates/helm.yml
  vars:
    helm_repo_name: '{{ software_ref.traefik.helm.repo_name }}'
    helm_repo_url: '{{ software_ref.traefik.helm.repo_url }}'
    helm_release_namespace: '{{ software_ref.traefik.helm.repo_name }}'
    helm_release_name: '{{ software_ref.traefik.helm.release_name }}'
    helm_chart_ref: '{{ software_ref.traefik.helm.repo_name }}/{{ software_ref.traefik.helm.chart_name }}'
    helm_chart_version: '{{ software_ref.traefik.helm.chart_version }}'
    helm_create_namespace: false
    helm_values_file: 'templates/01_traefik_gateway/traefik_values.yml'
    helm_wait: true