---
# Main keycloak instance
apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: keycloak
  namespace: ${ENVIRONMENT}-${ns_iam}
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-db
    database: keycloak
    port: 5432
    schema: keycloak-data
    usernameSecret:
      name: keycloak-owner-user.keycloak-db.credentials.postgresql.acid.zalan.do
      key: username
    passwordSecret:
      name: keycloak-owner-user.keycloak-db.credentials.postgresql.acid.zalan.do
      key: password
  http:
    serviceHttpPort: 8080
    httpEnabled: true
  hostname:
    hostname: https://iam.${DOMAIN}
    admin: https://iam.${DOMAIN}/admin
  proxy:
    headers: xforwarded 
  resources:
    limits:
      cpu: 450m
      memory: 600Mi
    requests:
      cpu: 150m
      memory: 200Mi
---
