- name: Install K3S
  hosts: main_server
  gather_facts: false

  vars_files:
    - vars/00_default.yml
    - vars/01_software_references.yml

  tasks:
    - name: Prepare server for K3S installation
      ansible.builtin.import_tasks: tasks/00_prepare_server.yml
      tags: [pre_install]

    - name: Install K3S on server
      ansible.builtin.import_tasks: tasks/01_install_k3s.yml
      tags: [install]

    - name: Create Kubeconfig file
      ansible.builtin.import_tasks: tasks/02_create_kubeconfig.yml
      tags: [kubeconfig]

    - name: Install CRDs
      delegate_to: localhost
      ansible.builtin.import_tasks: tasks/04_install_crds.yml
      when: inv_k8s.crds.enable
      tags: [crds]

    - name: Create Kubeconfig file
      delegate_to: localhost
      ansible.builtin.import_tasks: tasks/03_deploy_flux.yml
      when: inv_flux.enable
      tags: [flux]

    - name: Uninstall K3S
      ansible.builtin.shell: /usr/local/bin/k3s-uninstall.sh
      tags: [never, uninstall]