apiVersion: v1
data:
    data: ENC[AES256_GCM,data:bzIsJ+NCbnM=,iv:fn+nPSodJ9l5hA48yxEmKFSMOGzSikWQAWZg6IiP5bs=,tag:2j5xJoEvqN0rWMGiVgTKSg==,type:str]
kind: Secret
metadata:
    name: secret-test
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T09:07:58Z"
    mac: ENC[AES256_GCM,data:BzZ/AuywSnPrJQWGUoz7N4B6Jocg7ytAfex2uTNOBv4SDg7TwwSgVd70y/Ywuf/JKALGcGFCkkm4JercXkypcvcvjtJuJWCYNu+qRIz75/pYvfLXoKeRZBkr5+jWew2AJrLqDhIQQVebuQUfJHpBfYrqShpiL4D9h+JG06T1Hpo=,iv:ZEBvX8bCo0H0I+O2tRS11lhttuHx2X0rmPhY6gS8GOw=,tag:ol0rAl/LRtF7VTBmcpU5wA==,type:str]
    pgp:
        - created_at: "2026-06-21T09:07:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+9Ty15t9rgaAQ//aHeZC3dIqR7wrERoJzb0bJ/JXzj3dT+cT1pYfHLnFEeP
            tmLXVrJGelDlEes7oLn8Aksw1Eg/Yrw7HSRhkMQFvDQ2nscQqrM3qWZ6+27p2uQx
            JcUQbNIxu81ILJAWYjEqAcarPDJtwyqLv5r050WyhWQTpeTKFSomFdLnifEUuiEh
            RgeuD3uTmqW1QoQIgS9c1xWCvyXJgVHcHL/kFoFajaMmv+l0cfNtlx+iaGJyAJ6N
            poTtkITdhHdGKg53RhR1UB0a1I6zPb8ilb9ThzPgdlb8PhClIS7ltjGgVWNjaLv9
            lhaCOR7I6HeZn8pyrLSMQ15+HkFhJ1DueIb9EBPdhSKtiFhlfJhPRVnfncKl42gq
            kOzzA21zuR471/ZLmYOZovS+JQPx8pYpz/+ymAvLpcdd2xisPtr8gNOkuzQOOLuZ
            9f2v9bxy7USJWm7LWx0Ma9SiWdmDHTmNcY9WvEod2UCGQ2+W/p7ucaMV9zCqWcWu
            0aO0t6Zpersx3SA7yZUe1H7jdScDXjc3dMdEvdYG9kAcpVOmfnEoLkhg4f3QA/jh
            vXRt1mh9rY9ClTYRnCU8RpAvksW3ucAP03dUMcGscxWiCjGFmxP5OrGDwsZM3WkC
            3JQTA2HRGMA3hXB61D/GsMxkROmqLZfFJkHzOzhvXiJ7yNWk++BGBn1htG4wTAHS
            XAFseCCzNpCMPpzQLB32M3kBLalATZWV2dxt5Ntb/ZB7XD8SW2uQko63Tid+MKNO
            gGT9D4vxrky9RiT1kqbjA2nh6ikLUHJoai0akJ0xz/JTWopzzQD4CQFFBCKZ
            =ibwd
            -----END PGP MESSAGE-----
          fp: 87A45A3C61D4F0D73CA58C301EACAB6F74E400AB
    version: 3.13.1
