apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets-common
  namespace: flux-system
stringData:
  ## Github
  gh_runner_token:
  gh_config_token:

  ## Keycloak
  KC_INITIAL_USER:
  KC_INITIAL_PASSWORD:

  # Master Realm Admin User
  KC_ADMIN_USER:
  KC_ADMIN_PASSWORD:

  # App Realm Admin - Realm is named after the environment
  KC_APP_REALM:
  KC_APP_ADMIN_USER:
  KC_APP_ADMIN_PASSWORD:

  # Keycloak client secrets
  KC_CLIENT_SECRET_GRAFANA:
  KC_CLIENT_SECRET_VAULTWARDEN:

  # Vaultwarden
  VW_ADMIN_TOKEN: