apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars-common
  namespace: flux-system
data:
  DOMAIN:
  ENVIRONMENT:

  ## K8S Global Vars
  k8s_storage_class:

  ## Namespaces
  ns_monitoring:
  ns_operation:
  ns_traefik:
  ns_iam:
  ns_utils:
  ns_public:

  ## Github
  gh_runner_name:
  gh_config_url:

  ## Cert Manager
  cm_cluster_issuer_prd:
  cm_cluster_issuer_stg:
  cm_email:

  ## Traefik
  tr_gateway_class:
  tr_gateway:
  tr_controller_name:
  tr_listener_set_prd:
  tr_listener_set_stg:

  ## Pihole
  # List of DNS: https://docs.pi-hole.net/guides/dns/upstream-dns-providers/
  PH_DNS_UPSTREAMS: # https://docs.pi-hole.net/docker/configuration/#__tabbed_1_1