apiVersion: v1
kind: ConfigMap
metadata:
  name: gha-runner-controller-helm-values
  namespace: ${ENVIRONMENT}-${ns_utils}
data:
  values.yml: |-
    replicaCount: 1

    image:
      repository: "ghcr.io/actions/gha-runner-scale-set-controller"
      pullPolicy: IfNotPresent
      tag: 0.14.2

    flags:
      logLevel: "debug"
      logFormat: "text"

    resources:
      limits:
        cpu: 250m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gha-runner-helm-values
  namespace: ${ENVIRONMENT}-${ns_utils}
data:
  values.yml: |-
    githubConfigUrl: ${gh_config_url}
    githubConfigSecret:
      github_token: ${gh_config_token}

    runnerScaleSetName: ${gh_runner_name}

    minRunners: 0
    maxRunners: 2

    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:2.336.0
            command: ["/home/runner/run.sh"]
            env:
              - name: ACTIONS_RUNNER_CONTAINER_HOOKS
                value: /home/runner/k8s/index.js
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "true"
              - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
                value: /etc/gha-hook-extension/template.yml
              - name: ACTIONS_RUNNER_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
            volumeMounts:
              - name: gha-hook-extension
                mountPath: /etc/gha-hook-extension/template.yml
                subPath: template.yml
              - name: work
                mountPath: /home/runner/_work
        volumes:
          - name: gha-hook-extension
            configMap:
              name: gha-hook-extension
              items:
                - key: template.yml
                  path: template.yml
          - name: work
            ephemeral:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  storageClassName: ${k8s_storage_class}
                  resources:
                    requests:
                      storage: 1Gi
---
