apiVersion: v1
kind: ConfigMap
metadata:
  name: gha-runner-controller-helm-values
  namespace: ${ENVIRONMENT}-${ns_utils}
data:
  values.yml: |-
    replicaCount: 1

    image:
      repository: "ghcr.io/actions/gha-runner-scale-set-controller"
      pullPolicy: IfNotPresent
      tag: 0.14.2

    flags:
      logLevel: "debug"
      logFormat: "text"

    resources:
      limits:
        cpu: 250m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gha-runner-helm-values
  namespace: ${ENVIRONMENT}-${ns_utils}
data:
  values.yml: |-
    githubConfigUrl: ${gh_config_url}
    githubConfigSecret:
      github_token: ${gh_config_token}

    runnerScaleSetName: ${gh_runner_name}

    minRunners: 0
    maxRunners: 2

    template:
      spec:
        initContainers:
        - name: init-dind-externals
          image: ghcr.io/actions/actions-runner:2.336.0
          command: ["cp", "-r", "/home/runner/externals/.", "/home/runner/tmpDir/"]
          volumeMounts:
            - name: dind-externals
              mountPath: /home/runner/tmpDir
        - name: dind
          image: docker:dind
          args:
            - dockerd
            - --host=unix:///var/run/docker.sock
            - --group=$(DOCKER_GROUP_GID)
          env:
            - name: DOCKER_GROUP_GID
              value: "123"
          securityContext:
            privileged: true
          restartPolicy: Always
          startupProbe:
            exec:
              command:
                - docker
                - info
            initialDelaySeconds: 0
            failureThreshold: 24
            periodSeconds: 5
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: dind-sock
              mountPath: /var/run
            - name: dind-externals
              mountPath: /home/runner/externals
        containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
          env:
            - name: DOCKER_HOST
              value: unix:///var/run/docker.sock
            - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
              value: "120"
            - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
              value: /etc/gha-hook-extension/template.yml
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: dind-sock
              mountPath: /var/run
            - name: gha-hook-extension
              mountPath: /etc/gha-hook-extension/template.yml
              subPath: template.yml
        volumes:
        - name: work
          emptyDir: {}
        - name: dind-sock
          emptyDir: {}
        - name: dind-externals
          emptyDir: {}
        - name: gha-hook-extension
          configMap:
            name: gha-hook-extension
            items:
              - key: template.yml
                path: template.yml
---
