apiVersion: v1
kind: ServiceAccount
metadata:
  name: gha-runner-workflows
  namespace: ${ENVIRONMENT}-${ns_utils}
---
apiVersion: v1
kind: Secret
metadata:
  name: gha-runner-workflows
  namespace: ${ENVIRONMENT}-${ns_utils}
  annotations:
    kubernetes.io/service-account.name: gha-runner-workflows
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gha-runner-workflows
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

  - apiGroups: ["k8s.keycloak.org"]
    resources: ["keycloaks"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gha-runner-workflows
  namespace: ${ENVIRONMENT}-${ns_utils}
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: gha-runner-workflows
    namespace: ${ENVIRONMENT}-${ns_utils}

roleRef:
  kind: ClusterRole
  name: gha-runner-workflows
  apiGroup: rbac.authorization.k8s.io
---
