# Service account and RBAC for workflow pods
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gha-runner-workflow
  namespace: ${ENVIRONMENT}-${ns_utils}
---
apiVersion: v1
kind: Secret
metadata:
  name: gha-runner-workflow
  namespace: ${ENVIRONMENT}-${ns_utils}
  annotations:
    kubernetes.io/service-account.name: gha-runner-workflow
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gha-runner-workflow
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

  - apiGroups: ["k8s.keycloak.org"]
    resources: ["keycloaks", "keycloaks/status"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gha-runner-workflow
  namespace: ${ENVIRONMENT}-${ns_utils}
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: gha-runner-workflow
    namespace: ${ENVIRONMENT}-${ns_utils}

roleRef:
  kind: ClusterRole
  name: gha-runner-workflow
  apiGroup: rbac.authorization.k8s.io
---
# https://docs.github.com/en/actions/how-tos/manage-runners/use-actions-runner-controller/deploy-runner-scale-sets#configuring-hook-extensions
# Configmap for workflow pods
apiVersion: v1
kind: ConfigMap
metadata:
  name: gha-hook-extension
  namespace: ${ENVIRONMENT}-${ns_utils}
data:
  template.yml: |-
    spec:
      serviceAccountName: gha-runner-workflow
      containers:
        - name: "$job" # Target the job container
---
