apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager/
  - github-runner/
  - keycloak/
  - kube-prometheus-stack/
  - loki-alloy/
  - postgres-operator/
  - traefik/
  - namespace.yml
