---
apiVersion: v1
kind: Namespace
metadata:
  name: ${ENVIRONMENT}-${ns_traefik}
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${ENVIRONMENT}-${ns_operation}
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${ns_traefik}
---
