apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-helm-values-mod
data:
  values.yml: |-
    image:  # @schema additionalProperties: false
      # -- Traefik image host registry
      registry: docker.io
      # -- Traefik image repository
      repository: traefik
      # -- defaults to appVersion. It's used for version checking, even prefixed with experimental- or latest-.
      # When a digest is required, `versionOverride` can be used to set the version.
      tag: v3.7.5  # @schema type:[string, null]
      # -- Traefik image pull policy
      pullPolicy: IfNotPresent

    deployment:
      # -- Number of pods of the deployment (only applies when kind == Deployment)
      replicas: 1

    # -- [Resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) for `traefik` container.
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits: {} # Limits left out as traefik is a critical component
