apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-helm-values
data:
  values.yml: |-
    image:
      registry: docker.io
      repository: traefik
      tag: v3.7.5
      pullPolicy: IfNotPresent

    deployment:
      enabled: true
      replicas: 1

    ingressClass:
      enabled: false

    gateway:
      enabled: true

    gatewayClass: 
      enabled: true

    api:
      dashboard: true

    ingressRoute:
      dashboard:
        enabled: false

    providers:
      kubernetesCRD:
        enabled: false

      kubernetesIngress:
        enabled: false

      kubernetesGateway:
        enabled: true

      kubernetesIngressNGINX:
        enabled: false

    log:
      level: INFO

    metrics:
      addInternals: false
      prometheus: null

    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits: {} # Limits left out as traefik is a critical component
