---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-helm-values
  namespace: ${ENVIRONMENT}-${ns_data}
data:
  values.yml: |-
    image:
      registry: docker.io
      repository: grafana/grafana
      tag: 12.3.1
      sha: ""
      pullPolicy: IfNotPresent

    env:
      GF_SERVER_ROOT_URL: https://grafana.${DOMAIN}
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_OAUTH_AUTO_LOGIN: false
      GF_AUTH_DISABLE_SIGNOUT_MENU: false
      GF_AUTH_GENERIC_OAUTH_ENABLED: true
      GF_AUTH_GENERIC_OAUTH_NAME: KEYCLOAK
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: true
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: grafana
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ${KC_CLIENT_SECRET_GRAFANA}
      GF_AUTH_GENERIC_OAUTH_SCOPES: openid email profile offline_access roles
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://iam.${DOMAIN}/realms/${KC_APP_REALM}/protocol/openid-connect/auth
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://iam.${DOMAIN}/realms/${KC_APP_REALM}/protocol/openid-connect/token
      GF_AUTH_GENERIC_OAUTH_API_URL: https://iam.${DOMAIN}/realms/${KC_APP_REALM}/protocol/openid-connect/userinfo
      GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: username
      GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: username
      GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH: email
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: contains(resource_access.grafana.roles[*], 'grafanaServerAdmin') && 'grafanaAdmin' || contains(resource_access.grafana.roles[*], 'grafanaAdmin') && 'Admin' || contains(resource_access.grafana.roles[*], 'grafanaEditor') && 'Editor' || contains(resource_access.grafana.roles[*], 'grafanaViewer') && 'Viewer' || ''

    createConfigmap: true

    persistence:
      type: pvc
      enabled: false
      storageClassName: ${k8s_storage_class}
      volumeName: ""
      accessModes:
        - ReadWriteOnce
      size: 10Gi

    downloadDashboardsImage:
      registry: docker.io
      repository: curlimages/curl
      tag: 8.9.1
      sha: ""
      pullPolicy: IfNotPresent

    sidecar:
      image:
        registry: quay.io
        repository: kiwigrid/k8s-sidecar
        tag: 2.5.0
        sha: ""
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 20m
          memory: 20Mi
      provider:
        foldersFromFilesStructure: true
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        searchNamespace: ALL
        defaultFolderName: null
        folderAnnotation: "grafana_folder"
      datasources:
        enabled: true
        label: grafana_datasource
        labelValue: "1"
        searchNamespace: ALL

    downloadDashboards:
      env: {}
      envFromSecret: ""
      resources: {}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        seccompProfile:
          type: RuntimeDefault
      envValueFrom: {}

    serviceMonitor:
      enabled: true
      path: /metrics
      namespace: ${ENVIRONMENT}-${ns_monitoring}

    ingress:
      enabled: false

    resources:
      limits:
        cpu: 400m
        memory: 750Mi
      requests:
        cpu: 150m
        memory: 400Mi

    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          uid: prometheus
          url: http://kube-prometheus-stack-prometheus.${ENVIRONMENT}-${ns_monitoring}:9090
          access: proxy
          isDefault: true
---
