apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars-common
  namespace: flux-system
data:
  DOMAIN: 
  ENVIRONMENT: dev

  ## Kubernetes variables
  K8S_CLUSTER_ISSUER: letsencrypt-production

  ## Namespaces
  ns_monitoring:
  ns_operation:
  ns_traefik:
