apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars-common
  namespace: flux-system
data:
  DOMAIN:
  ENVIRONMENT:

  ## Namespaces
  ns_monitoring:
  ns_operation:
  ns_traefik:
  ns_iam:

  ## Cert Manager
  cm_cluster_issuer_prd:
  cm_cluster_issuer_stg:
  cm_email:

  ## Traefik
  tr_gateway_class:
  tr_gateway:
  tr_controller_name:
  tr_listener_set_prd:
  tr_listener_set_stg:

  ## IAM
  iam_db_replicas: 