---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./03_infrastructure/01_controllers
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-config
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 5m
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./03_infrastructure/02_configs
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---