---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: ${ns_traefik}
  annotations:
    cert-manager.io/cluster-issuer: ${K8S_CLUSTER_ISSUER}
spec:
  gatewayClassName: traefik

  listeners:
    - name: http-default
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All 

    - name: monitoring-grafana
      hostname: monitoring.${DOMAIN}
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: monitoring-grafana-tls
            kind: Secret
            group: ""

      allowedRoutes:
        namespaces:
          from: All
