---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ${tr_gateway}
  namespace: ${ns_traefik}
  annotations:
    cert-manager.io/cluster-issuer: ${cm_cluster_issuer_prd}
spec:
  gatewayClassName: ${tr_gateway_class}

  # allowedListeners:
  #   namespaces:
  #     from: All

  # https://github.com/kubernetes-sigs/gateway-api/issues/4425
  listeners:
    - name: http
      protocol: HTTP
      port: 8000
      allowedRoutes:
          namespaces:
            from: All

    - name: grafana
      hostname: grafana.${DOMAIN}
      protocol: HTTPS
      port: 8443
      tls:
        mode: Terminate
        certificateRefs:
          - name: grafana-tls
            kind: Secret
            group: ""

      allowedRoutes:
        namespaces:
          from: All

    - name: keycloak
      hostname: iam.${DOMAIN}
      protocol: HTTPS
      port: 8443
      tls:
        mode: Terminate
        certificateRefs:
          - name: keycloak-tls
            kind: Secret
            group: ""

      allowedRoutes:
        namespaces:
          from: All

    - name: keycloak-admin
      hostname: iam-admin.${DOMAIN}
      protocol: HTTPS
      port: 8443
      tls:
        mode: Terminate
        certificateRefs:
          - name: keycloak-admin-tls
            kind: Secret
            group: ""

      allowedRoutes:
        namespaces:
          from: All

    - name: jellyfin
      hostname: jellyfin.${DOMAIN}
      protocol: HTTPS
      port: 8443
      tls:
        mode: Terminate
        certificateRefs:
          - name: jellyfin-tls
            kind: Secret
            group: ""

      allowedRoutes:
        namespaces:
          from: All

    - name: vaultwarden
      hostname: vaultwarden.${DOMAIN}
      protocol: HTTPS
      port: 8443
      tls:
        mode: Terminate
        certificateRefs:
          - name: vaultwarden-tls
            kind: Secret
            group: ""

      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ${tr_gateway}-staging
  namespace: ${ns_traefik}
  annotations:
    cert-manager.io/cluster-issuer: ${cm_cluster_issuer_stg}
spec:
  gatewayClassName: ${tr_gateway_class}

  listeners:
    - name: http
      protocol: HTTP
      port: 8000
      allowedRoutes:
          namespaces:
            from: All

    # - name: keycloak
    #   hostname: iam.${DOMAIN}
    #   protocol: HTTPS
    #   port: 8443
    #   tls:
    #     mode: Terminate
    #     certificateRefs:
    #       - name: keycloak-tls
    #         kind: Secret
    #         group: ""

    #   allowedRoutes:
    #     namespaces:
    #       from: All
---
