---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: ${ENVIRONMENT}-${ns_public}
spec:
  parentRefs:
    - name: ${tr_gateway} # ${tr_listener_set_prd}
      sectionName: grafana
      group: gateway.networking.k8s.io
      kind: Gateway # ListenerSet
      namespace: ${ns_traefik}

  hostnames:
    - grafana.${DOMAIN}

  rules:
     - matches:
        - path:
            type: PathPrefix
            value: /

       backendRefs:
        - name: grafana
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak
  namespace: ${ENVIRONMENT}-${ns_iam}
spec:
  parentRefs:
    - name: ${tr_gateway}
      sectionName: keycloak
      group: gateway.networking.k8s.io
      kind: Gateway
      namespace: ${ns_traefik}

  hostnames:
    - iam.${DOMAIN}

  rules:
     - matches:
        - path:
            type: PathPrefix
            value: /

       backendRefs:
        - name: keycloak-service
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-admin
  namespace: ${ENVIRONMENT}-${ns_iam}
spec:
  parentRefs:
    - name: ${tr_gateway}
      sectionName: keycloak-admin
      group: gateway.networking.k8s.io
      kind: Gateway
      namespace: ${ns_traefik}

  hostnames:
    - iam-admin.${DOMAIN}

  rules:
     - matches:
        - path:
            type: PathPrefix
            value: /

       backendRefs:
        - name: keycloak-service
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin
  namespace: ${ENVIRONMENT}-${ns_public}
spec:
  parentRefs:
    - name: ${tr_gateway}
      sectionName: jellyfin
      group: gateway.networking.k8s.io
      kind: Gateway
      namespace: ${ns_traefik}

  hostnames:
    - jellyfin.${DOMAIN}

  rules:
     - matches:
        - path:
            type: PathPrefix
            value: /

       backendRefs:
        - name: jellyfin
          port: 8096
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vaultwarden
  namespace: ${ENVIRONMENT}-${ns_public}
spec:
  parentRefs:
    - name: ${tr_gateway}
      sectionName: vaultwarden
      group: gateway.networking.k8s.io
      kind: Gateway
      namespace: ${ns_traefik}

  hostnames:
    - vaultwarden.${DOMAIN}

  rules:
     - matches:
        - path:
            type: PathPrefix
            value: /

       backendRefs:
        - name: vaultwarden
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pi-hole
  namespace: ${ENVIRONMENT}-${ns_utils}
spec:
  parentRefs:
    - name: ${tr_gateway}
      sectionName: pi-hole
      group: gateway.networking.k8s.io
      kind: Gateway
      namespace: ${ns_traefik}

  hostnames:
    - pi-hole.${DOMAIN}

  rules:
     - matches:
        - path:
            type: PathPrefix
            value: /

       backendRefs:
        - name: pi-hole-svc
          port: 80
---
