---
# For env explanation, see https://docs.pi-hole.net/ftldns/configfile
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-hole
  namespace: ${ENVIRONMENT}-${ns_utils}
  labels:
    app: pi-hole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi-hole
  template:
    metadata:
      labels:
        app: pi-hole
    spec:
      containers:
        - name: pi-hole
          image: pihole/pihole:2026.07.2
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          env:
            - name: TZ
              value: Europe/Berlin
            - name: FTLCONF_dns_upstreams
              value: "127.0.0.1#53"
            - name: FTLCONF_dns_CNAMEdeepInspect
              value: "true"
            - name: FTLCONF_dns_ignoreLocalhost
              value: "false"
            - name: FTLCONF_dns_listeningMode
              value: "LOCAL"
            - name: FTLCONF_webserver_api_password
              valueFrom:
                secretKeyRef:
                  name: pihole-secret
                  key: PH_UI_PASSWORD
          volumeMounts:
            - mountPath: /etc/pihole
              name: pi-hole-pvc
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME", "SYS_NICE"]
          resources:
            limits:
              cpu: 200m
              memory: 250Mi
            requests:
              cpu: 80m
              memory: 100Mi

        - name: unbound
          image: klutchell/unbound:1.26.0
          volumeMounts:
            - mountPath: /etc/unbound/conf.d/pi-hole.conf
              subPath: pi-hole.conf
              name: unbound-config
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 40m
              memory: 50Mi

      volumes:
        - name: pi-hole-pvc
          persistentVolumeClaim:
            claimName: pi-hole-pvc
        - name: unbound-config
          configMap:
            name: unbound-config
            items:
              - key: pi-hole.conf
                path: pi-hole.conf
---
