---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-pvc
  namespace: ${ENVIRONMENT}-${ns_utils}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ${k8s_storage_class}
---

