---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-pvc
  namespace: ${ENVIRONMENT}-${ns_utils}
spec:
  storageClassName: ${k8s_storage_class}
  volumeName: pi-hole-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pi-hole-pv
  namespace: ${ENVIRONMENT}-${ns_utils}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ${k8s_storage_class}
---
