# Test file
name: .Test Github Actions workflows

on:
  # Manual trigger
  workflow_dispatch:

env:
  COMMIT_MSG: ${{ github.event.head_commit.message }}

jobs:
  # First test
  test_0:
    # Evaluate last commit message
    if: ${{ contains($COMMIT_MSG, '#wf_test_0') }}
    runs-on: homelab-gha-runner
    environment: workflow-test
    container:
      image: ubuntu:22.04
    steps:
      - run: echo Hello world!!!

  # Test creating env file from secret and view encryption
  test_1:
    if: ${{ contains($COMMIT_MSG, '#wf_test_1') }}
    runs-on: homelab-gha-runner
    environment: workflow-test
    container:
      image: ubuntu:22.04
    steps:
      - name: Create env file
        run: |-
          touch .env
          echo ${{ secrets.TEST_ENV }} > .env
          source .env
      
      - name: Use test API key 1
        run: |-
          curl --verbose --header "API-Key: $API_KEY_1" www.google.com
        continue-on-error: true

      - name: Use test API key 2
        run: |-
          curl --verbose --header "API-Key: $API_KEY_2" www.google.com
        continue-on-error: true