# Test file
name: .test Github Actions workflows

on:
  push

env:
  SCRIPT_PATH: ./05_scripts/.test_scripts

jobs:
  ### First test
  test_0:
    # Evaluate last commit message
    if: ${{ contains(github.event.head_commit.message, '#wf_test_0') }}
    runs-on: homelab-gha-runner
    environment: workflow-test
    container:
      image: ubuntu
    steps:
      - run: echo Hello world!!!

  ### Test encryption using file as secret
  test_1:
    if: ${{ contains(github.event.head_commit.message, '#wf_test_1') }}
    runs-on: homelab-gha-runner
    environment: workflow-test
    container:
      image: ghcr.io/nivesh00/utillity-tools
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v7

      - name: Run a script
        run: $SCRIPT_PATH/01_test_curl.sh
        env:
          TEST_ENV: ${{ secrets.TEST_ENV }}