name: 01 - Set up Keycloak

on: workflow_dispatch

jobs:
  setup_keycloak:
    runs-on: homelab-gha-runner
    container:
      image: ghcr.io/nivesh00/utility-tools
    environment: homelab
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Switch to Kubernetes script directory, create .env file from secrets and run script
      - name: Wait for Keycloak to be ready
        run: |-
          cd 05_scripts/kubernetes
          pip install --no-cache-dir -r requirements.txt
          echo "${{ secrets.KUBERNETES_ENV }}" >&1 > .env
          python3 01_wait_for_resource.py --load-env --incluster

      # Switch to Keycloak scripts directory, create .env file from secrets and run script
      - name: Setup Keycloak users and realms
        run: |-
          cd 05_scripts/keycloak
          pip install --no-cache-dir -r requirements.txt
          echo "${{ secrets.KEYCLOAK_ENV }}" >&1 > .env
          python3 01_create_user_and_realm.py --load-env
      
      # Switch to Keycloak directory and run script
      - name: Setup Keycloak clients and roles
        run: |-
          cd 05_scripts/keycloak
          python3 02_create_clients_and_roles.py --load-env

