name: 01 - Set up Keycloak

on: workflow_dispatch

jobs:
  checkout_code:
    runs-on: homelab-gha-runner
    container:
      image: ghcr.io/nivesh00/utility-tools
    environment: homelab
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Do not get extra git branches to save time

      - name: Upload scripts as artifact for later use
        uses: actions/upload-artifact@v7
        with:
          name: scripts-directory
          path: 05_scripts

  wait_for_keycloak_resource:
    needs: checkout_code
    runs-on: homelab-gha-runner
    container:
      image: ghcr.io/nivesh00/utility-tools
    environment: homelab
    steps:
      - name: Download scripts artifact
        uses: actions/download-artifact@v8
        with:
          name: scripts-directory
          path: ./05_scripts

      - run: ls -aR

      - name: Switch to Kubernetes scripts directory
        run: cd 05_scripts/kubernetes

      - name: Load ENV file
        run: echo "${{ secrets.KUBERNETES_ENV }}" > .env
      
      - name: Install Python modules
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run script
        run: python3 01_wait_for_resource.py --load-env --incluster

  setup_keycloak:
    if: false
    needs: wait_for_keycloak_resource
    runs-on: homelab-gha-runner
    container:
      image: ghcr.io/nivesh00/utility-tools
    environment: homelab
    steps:
      - name: Download scripts artifact
        uses: actions/download-artifact@v8
        with:
          name: scripts-directory
          path: ./05_scripts

      - name: Switch to Keycloak scripts directory
        run: cd 05_scripts/keycloak
      
      - name: Load ENV file
        run: echo "${{ secrets.KEYCLOAK_ENV }}" > .env
      
      - name: Install Python modules
        run: pip install --no-cache-dir -r requirements.txt
      
      - name: Run script
        run: python3 01_create_user_and_realm.py --load-env