name: Test action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: homelab-gha-runner
    environment: homelab
    container:
      image: ubuntu:22.04
    steps:
      - run: echo Hello world!!!
