name: Test self hosted action

# Trigger manually
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: homelab-gha-runner
    environment: homelab
    container:
      image: ubuntu:22.04
    steps:
      - run: echo Hello world!!!
